services:
    traefik:
        image: traefik:v3.0
        volumes:
            - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./config/traefik/dynamic:/etc/traefik/dynamic:ro
            - ./data/traefik:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
        networks:
            - traefik

    whoami:
        image: traefik/whoami
        container_name: whoami
        networks:
            - traefik

networks:
    traefik:
        driver: bridge
