services:
    traefik:
        image: traefik:v3.0
        command:
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
            - "--certificatesresolvers.cloudflare.acme.email=bojurgess@gmail.com"
            - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
            - "--log.level=DEBUG"
            - "--api=true"
            - "--api.dashboard=true"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
            - TRAEFIK_AUTH_HASH=${TRAEFIK_AUTH_HASH}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/traefik/acme.json:/letsencrypt/acme.json
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.traefik.rule=Host(`traefik.beno.lol`)"
            - "traefik.http.routers.traefik.entrypoints=websecure"
            - "traefik.http.routers.traefik.tls=true"
            - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
            - "traefik.http.routers.traefik.service=api@internal"
            - "traefik.http.routers.traefik.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH_HASH}"
        networks:
            - traefik

    whoami:
        image: traefik/whoami
        container_name: whoami
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`mc.beno.lol`) && PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami.entrypoints=websecure"
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.tls.certresolver=cloudflare"
            - "traefik.http.routers.whoami.middlewares=strip-whoami"
            - "traefik.http.middlewares.strip-whoami.stripPrefix.prefixes=/whoami"
        ports:
            - "8080:80"
        networks:
            - traefik

networks:
    traefik:
        driver: bridge
