server:
<<<<<<< HEAD
  name: "smp"
metrics:
  enabled: true
  driver: "prometheus"
  collectors:
    systemGc: true
    systemMemory: true
    systemProcess: true
    systemThread: true
    server: true
    world: true
    tick: true
    events: true
=======
    name: "smp"
metrics:
    enabled: true
    driver: "prometheus"
    collectors:
        systemGc: true
        systemMemory: true
        systemProcess: true
        systemThread: true
        server: true
        world: true
        tick: true
        events: true
>>>>>>> 1ae7836bd65a5ec5760f8f94d1a498c31057e5fc
